#Tasks should be executed from this branch
branch: master

#List of Available tasks
tasks:
  - build:
      cmd: mvn clean install
  - compress:
      cmd: zip -r scripting.zip target/
  - integration:
      cmd: mvn verify
  - deploy: 
      cmd: scp deploy.sh scripting.zip ec2-user@3.91.161.153:/home/ec2-user; ssh ec2-user@3.91.161.153"sudo sh /home/ec2-user/deploy.sh"


#Pipeline execution order way to run my steps
pipelines:
  - build:
     - build
  - release:
      - build
      - integration
      - compress
      - deploy
  - foo:
     - invalid
      
